### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by roosfeld** [eriknn/ha-pax_ble#17]
After latest update I got error message and integration is not working. Could you please check?

From logs:

Error setting up entry PAX Calima for pax_ble
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pax_ble/__init__.py", line 30, in async_setup_entry
    scan_interval_fast = config_entry.data[CONF_SCAN_INTERVAL_FAST]
KeyError: 'scan_interval_fast'

![Screenshot 2023-02-28 at 13 37 36](https://user-images.githubusercontent.com/81015119/221843119-1e24f8fe-03ea-4411-866f-c1e4a6e9a8d7.png)
![Screenshot 2023-02-28 at 13 37 24](https://user-images.githubusercontent.com/81015119/221843124-7d489749-d0d4-4a7d-8002-bfb9f24a9ab9.png)

**Comment by eriknn** [comment]
Hi, I thought my update comment was visible?
I made changes to the config flow, added a variable. This means you must probably remove and add the fan again, so that the new variable is added to the config.
I think maybe there are ways I vould have done this without breaking it, but I’m haven’t read up on those parts of integrations :/

**Comment by roosfeld** [comment]
Thanks for the quick response and I managed to add the devices again, everything works again. Its a good feature and I'm very happy with the work that you have done. Thanks! If you need help with testing then I happy to help.

**Comment by eriknn** [comment]
Great, I’ll close the issue then 😀
