### ISSUE TITLE
Can´t add devices

### ISSUE THREAD

**Issue by zlakes01** [eriknn/ha-pax_ble#25]
![image](https://github.com/eriknn/ha-pax_ble/assets/132156054/032f60f8-9640-4f5b-bd5f-10ecf39585a8)

**Comment by eriknn** [comment]
Was it discovered automatically? If not, check the bluetooth logs to see discovered devices. I’m guessing it’s out of range…

**Comment by zlakes01** [comment]
Out of range is possible. I have to check it.

**Comment by zlakes01** [comment]
I couldn´t find bluetooths logs. Where is it?

**Comment by ivoh95** [comment]
I have a similar issue. It turns out I  had somehow gotten the fan in a buggy state where neither the phone app would find it nor HA. Power cycling the fan fixed it and it was automatically discovered then. Something easy to try if the phone app works at that distance or if a power cycle helps

**Comment by eriknn** [comment]
@zlakes01 Under "Bluetooth" and your adapter - select "Download diagnostics" or similar. This should show all discovered devices and signal strength (RSSI). Not sure how reliable that value is though.

@ivoh95 I have experienced the same thing once. But I've been doing lots of connecting/reconnecting while testing, so I'm not surprised that it was too much for the fan :)

**Comment by zlakes01** [comment]
It works after an update of Core. I see all three Pax Calima and can manage them.

**Comment by catellie** [comment]
May I chime in with a question here? I've had this integration working just fine for a long time (6+ months) and then I had to move my server a couple of meters sideways (yeah, it wasn't really pretty where I had it originally). Technically, it's actually slightly closer than before, though there is a bit more metal in the "line of sight" (two floors up partly through cement floor).
Interestingly, my io9 toothbrush is actually somewhat closer, but never had any issue. Anyway, after the move it went very glitchy so I tried to remove it in order to start over - bad idea I guess because now it pops up as a new device every day or so, but I never managed to reconnect it again. For kicks I tried installing a ESP32 M5Stack Atom Lite BT proxy which appears to make all the right moves, but still no connection. Do you @eriknn know whether it should be able to handle the Calima? Their app works fine and I can't _really_ say I need this integration much, I'm just sad it worked fine before the move and now it fails utterly.

**Comment by eriknn** [comment]
Sorry but I don’t know much about BT extenders, so I can really help you.
If the connection is that bad I would recommend using the ignore-function on the discovery, that should at least make it leave you alone :)
